In [1]:
import pandas as pd
import numpy as np

df=pd.read_csv("/content/supply_chain_dataset1.csv")
print(f"Rows & Columns : {df.shape}")

Rows & Columns : (91250, 15)

In [2]:
df.head()

,Date,SKU_ID,Warehouse_ID,Supplier_ID,Region,Units_Sold,Inventory_Level,Supplier_Lead_Time_Days,Reorder_Point,Order_Quantity,Unit_Cost,Unit_Price,Promotion_Flag,Stockout_Flag,Demand_Forecast
0,2024-01-01,SKU_1,WH_1,SUP_8,West,10,592,14,379,0,13.95,20.48,0,0,8.52
1,2024-01-02,SKU_1,WH_1,SUP_8,West,17,575,14,379,0,13.95,20.48,0,0,18.63
2,2024-01-03,SKU_1,WH_1,SUP_8,North,35,540,14,379,0,13.95,20.48,1,0,39.62
3,2024-01-04,SKU_1,WH_1,SUP_8,South,24,516,14,379,0,13.95,20.48,0,0,19.43
4,2024-01-05,SKU_1,WH_1,SUP_8,West,21,495,14,379,0,13.95,20.48,0,0,18.70

In [3]:
df.tail()

,Date,SKU_ID,Warehouse_ID,Supplier_ID,Region,Units_Sold,Inventory_Level,Supplier_Lead_Time_Days,Reorder_Point,Order_Quantity,Unit_Cost,Unit_Price,Promotion_Flag,Stockout_Flag,Demand_Forecast
91245,2024-12-26,SKU_50,WH_5,SUP_10,South,17,352,7,283,0,6.65,9.6,0,0,19.82
91246,2024-12-27,SKU_50,WH_5,SUP_10,South,21,331,7,283,0,6.65,9.6,0,0,27.96
91247,2024-12-28,SKU_50,WH_5,SUP_10,East,17,314,7,283,0,6.65,9.6,0,0,22.13
91248,2024-12-29,SKU_50,WH_5,SUP_10,South,24,290,7,283,0,6.65,9.6,1,0,24.11
91249,2024-12-30,SKU_50,WH_5,SUP_10,West,15,275,7,283,0,6.65,9.6,1,0,20.19

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91250 entries, 0 to 91249
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Date                     91250 non-null  object
 1   SKU_ID                   91250 non-null  object
 2   Warehouse_ID             91250 non-null  object
 3   Supplier_ID              91250 non-null  object
 4   Region                   91250 non-null  object
 5   Units_Sold               91250 non-null  int64
 6   Inventory_Level          91250 non-null  int64
 7   Supplier_Lead_Time_Days  91250 non-null  int64
 8   Reorder_Point            91250 non-null  int64
 9   Order_Quantity           91250 non-null  int64
 10  Unit_Cost                91250 non-null  float64
 11  Unit_Price               91250 non-null  float64
 12  Promotion_Flag           91250 non-null  int64
 13  Stockout_Flag            91250 non-null  int64
 14  Demand_Forecast          91250 non-null  float64
dtypes: float64(3), int64(7), object(5)
memory usage: 10.4+ MB

In [5]:
df["Date"] = pd.to_datetime(df["Date"])

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91250 entries, 0 to 91249
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Date                     91250 non-null  datetime64[ns]
 1   SKU_ID                   91250 non-null  object
 2   Warehouse_ID             91250 non-null  object
 3   Supplier_ID              91250 non-null  object
 4   Region                   91250 non-null  object
 5   Units_Sold               91250 non-null  int64
 6   Inventory_Level          91250 non-null  int64
 7   Supplier_Lead_Time_Days  91250 non-null  int64
 8   Reorder_Point            91250 non-null  int64
 9   Order_Quantity           91250 non-null  int64
 10  Unit_Cost                91250 non-null  float64
 11  Unit_Price               91250 non-null  float64
 12  Promotion_Flag           91250 non-null  int64
 13  Stockout_Flag            91250 non-null  int64
 14  Demand_Forecast          91250 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(7), object(4)
memory usage: 10.4+ MB

In [7]:
df.describe()

,Date,Units_Sold,Inventory_Level,Supplier_Lead_Time_Days,Reorder_Point,Order_Quantity,Unit_Cost,Unit_Price,Promotion_Flag,Stockout_Flag,Demand_Forecast
count,91250,91250.000000,91250.000000,91250.000000,91250.000000,91250.000000,91250.000000,91250.000000,91250.000000,91250.0,91250.000000
mean,2024-07-01 00:00:00,20.054564,471.522312,7.984000,300.068000,19.272493,12.203320,18.261800,0.101589,0.0,20.082033
min,2024-01-01 00:00:00,0.000000,168.000000,2.000000,201.000000,0.000000,5.020000,6.950000,0.000000,0.0,0.000000
25%,2024-04-01 00:00:00,13.000000,370.000000,4.000000,252.000000,0.000000,8.180000,12.000000,0.000000,0.0,12.950000
50%,2024-07-01 00:00:00,20.000000,461.000000,8.000000,300.000000,0.000000,11.990000,18.180000,0.000000,0.0,19.950000
75%,2024-09-30 00:00:00,27.000000,564.000000,11.000000,346.000000,0.000000,16.320000,23.390000,0.000000,0.0,26.930000
max,2024-12-30 00:00:00,59.000000,990.000000,14.000000,398.000000,499.000000,19.760000,35.100000,1.000000,0.0,61.420000
std,NaN,9.068602,133.488002,3.907929,54.879945,82.340831,4.574982,7.121136,0.302109,0.0,9.503955

In [8]:
unique_counts = df.nunique().sort_values(ascending=False)
unique_counts

Demand_Forecast            4736
Inventory_Level             781
Date                        365
Order_Quantity              301
Unit_Cost                   230
Unit_Price                  227
Reorder_Point               142
Units_Sold                   58
SKU_ID                       50
Supplier_Lead_Time_Days      13
Supplier_ID                  10
Warehouse_ID                  5
Region                        4
Promotion_Flag                2
Stockout_Flag                 1
dtype: int64

In [9]:
missing_values = df.isnull().sum()
missing_values

Date                       0
SKU_ID                     0
Warehouse_ID               0
Supplier_ID                0
Region                     0
Units_Sold                 0
Inventory_Level            0
Supplier_Lead_Time_Days    0
Reorder_Point              0
Order_Quantity             0
Unit_Cost                  0
Unit_Price                 0
Promotion_Flag             0
Stockout_Flag              0
Demand_Forecast            0
dtype: int64

In [10]:
duplicate_count = df.duplicated().sum()
print(f"Duplicate rows: {duplicate_count}")

Duplicate rows: 0

In [11]:
print("Minimum Date:", df["Date"].min())
print("Maximum Date:", df["Date"].max())
print("Number of Days:", df["Date"].nunique())

Minimum Date: 2024-01-01 00:00:00
Maximum Date: 2024-12-30 00:00:00
Number of Days: 365

We're trying to determine whether:

Warehouse_ID → Region

If every warehouse has exactly one region, then Region belongs in the Warehouses table.

In [12]:
df[["Warehouse_ID", "Region"]].drop_duplicates().sort_values("Warehouse_ID")

     Warehouse_ID Region
0            WH_1   West
2            WH_1  North
3            WH_1  South
5            WH_1   East
365          WH_2   East
366          WH_2  South
368          WH_2   West
369          WH_2  North
734          WH_3  South
732          WH_3  North
731          WH_3   East
730          WH_3   West
1095         WH_4   East
1096         WH_4  North
1099         WH_4  South
1102         WH_4   West
1460         WH_5   East
1461         WH_5   West
1462         WH_5  South
1465         WH_5  North

In [13]:
df[["Supplier_ID", "Supplier_Lead_Time_Days"]].drop_duplicates().sort_values("Supplier_ID")

      Supplier_ID  Supplier_Lead_Time_Days
25915       SUP_1                        8
15695       SUP_1                        3
36865       SUP_1                        7
73730       SUP_1                       13
38325       SUP_1                        4
...           ...                      ...
26280       SUP_9                        7
27375       SUP_9                       14
39055       SUP_9                        4
14965       SUP_9                       12
87235       SUP_9                       11

[113 rows x 2 columns]

In [14]:
df[["SKU_ID", "Unit_Cost", "Unit_Price", "Reorder_Point"]].drop_duplicates().sort_values("SKU_ID")

      SKU_ID  Unit_Cost  Unit_Price  Reorder_Point
0      SKU_1      13.95       20.48            379
365    SKU_1      11.46       19.92            322
730    SKU_1       6.06        8.41            314
1095   SKU_1       6.93       10.70            333
1460   SKU_1      19.41       23.81            366
...      ...        ...         ...            ...
16060  SKU_9       6.17        9.69            345
14600  SKU_9       9.87       13.54            254
14965  SKU_9      18.00       23.39            384
15330  SKU_9      10.01       15.85            307
15695  SKU_9      10.90       18.04            323

[250 rows x 4 columns]

Mapping of Warehouse to Region

In [15]:
warehouse_dependency = (
    df.groupby("Warehouse_ID")["Region"].nunique()
    )
warehouse_dependency

Warehouse_ID
WH_1    4
WH_2    4
WH_3    4
WH_4    4
WH_5    4
Name: Region, dtype: int64

Testing Supplier -> Lead Time

In [16]:
supplier_dependency = (
    df.groupby("Supplier_ID")["Supplier_Lead_Time_Days"]
      .nunique()
)

supplier_dependency

Supplier_ID
SUP_1     12
SUP_10    10
SUP_2     11
SUP_3     12
SUP_4     10
SUP_5     11
SUP_6     11
SUP_7     11
SUP_8     13
SUP_9     12
Name: Supplier_Lead_Time_Days, dtype: int64

Test SKU → Unit Cost

In [17]:
sku_cost_dependency = (
    df.groupby("SKU_ID")["Unit_Cost"]
      .nunique()
)

sku_cost_dependency

SKU_ID
SKU_1     5
SKU_10    5
SKU_11    5
SKU_12    5
SKU_13    5
SKU_14    5
SKU_15    5
SKU_16    5
SKU_17    5
SKU_18    5
SKU_19    5
SKU_2     5
SKU_20    5
SKU_21    5
SKU_22    5
SKU_23    5
SKU_24    5
SKU_25    5
SKU_26    5
SKU_27    5
SKU_28    5
SKU_29    5
SKU_3     5
SKU_30    4
SKU_31    5
SKU_32    5
SKU_33    5
SKU_34    5
SKU_35    5
SKU_36    5
SKU_37    5
SKU_38    5
SKU_39    5
SKU_4     5
SKU_40    5
SKU_41    5
SKU_42    5
SKU_43    5
SKU_44    5
SKU_45    5
SKU_46    5
SKU_47    5
SKU_48    5
SKU_49    5
SKU_5     5
SKU_50    5
SKU_6     5
SKU_7     5
SKU_8     5
SKU_9     5
Name: Unit_Cost, dtype: int64

Test SKU → Unit Price

In [18]:
sku_price_dependency = (
    df.groupby("SKU_ID")["Unit_Price"]
      .nunique()
)

sku_price_dependency

SKU_ID
SKU_1     5
SKU_10    5
SKU_11    5
SKU_12    5
SKU_13    5
SKU_14    5
SKU_15    5
SKU_16    5
SKU_17    5
SKU_18    5
SKU_19    5
SKU_2     5
SKU_20    5
SKU_21    5
SKU_22    5
SKU_23    5
SKU_24    5
SKU_25    5
SKU_26    5
SKU_27    5
SKU_28    5
SKU_29    5
SKU_3     5
SKU_30    5
SKU_31    5
SKU_32    5
SKU_33    5
SKU_34    5
SKU_35    5
SKU_36    5
SKU_37    5
SKU_38    5
SKU_39    5
SKU_4     5
SKU_40    5
SKU_41    5
SKU_42    5
SKU_43    5
SKU_44    5
SKU_45    5
SKU_46    5
SKU_47    5
SKU_48    5
SKU_49    5
SKU_5     5
SKU_50    5
SKU_6     5
SKU_7     5
SKU_8     5
SKU_9     5
Name: Unit_Price, dtype: int64

Test SKU → Reorder Point

In [19]:
sku_reorder_dependency = (
    df.groupby("SKU_ID")["Reorder_Point"]
      .nunique()
)

sku_reorder_dependency

SKU_ID
SKU_1     5
SKU_10    5
SKU_11    5
SKU_12    5
SKU_13    5
SKU_14    5
SKU_15    5
SKU_16    5
SKU_17    5
SKU_18    5
SKU_19    5
SKU_2     5
SKU_20    5
SKU_21    5
SKU_22    5
SKU_23    5
SKU_24    5
SKU_25    5
SKU_26    5
SKU_27    5
SKU_28    5
SKU_29    4
SKU_3     5
SKU_30    5
SKU_31    5
SKU_32    5
SKU_33    5
SKU_34    5
SKU_35    4
SKU_36    4
SKU_37    5
SKU_38    5
SKU_39    5
SKU_4     5
SKU_40    5
SKU_41    5
SKU_42    5
SKU_43    5
SKU_44    5
SKU_45    5
SKU_46    5
SKU_47    5
SKU_48    5
SKU_49    5
SKU_5     5
SKU_50    5
SKU_6     5
SKU_7     5
SKU_8     5
SKU_9     5
Name: Reorder_Point, dtype: int64

Noe let us check SKU + Warehouse dependency

In [20]:
sku_warehouse_reorder = (
    df.groupby(
        ["SKU_ID", "Warehouse_ID"]
    )["Reorder_Point"]
    .nunique()
)

sku_warehouse_reorder.max()

1

This means:

SKU_ID + Warehouse_ID

        ↓
Reorder_Point

Reorder_Point belongs to an inventory-level entity rather than the product master.

In [21]:
df["Stockout_Flag"].value_counts()

Stockout_Flag
0    91250
Name: count, dtype: int64

Stockout_Flag has no variation and therefore cannot currently support meaningful stockout-event analysis.

### Promotion Analysis

In [22]:
df["Promotion_Flag"].value_counts()

Promotion_Flag
0    81980
1     9270
Name: count, dtype: int64

In [23]:
promotion_summary = (
    df.groupby("Promotion_Flag")
      .agg(
          Records=("SKU_ID", "size"),
          Avg_Units_Sold=("Units_Sold", "mean"),
          Total_Units_Sold=("Units_Sold", "sum")
      )
      .reset_index()
)

promotion_summary

   Promotion_Flag  Records  Avg_Units_Sold  Total_Units_Sold
0               0    81980       19.504977           1599018
1               1     9270       24.914887            230961

Creating Product Master

In [31]:
products = df[["SKU_ID"]].drop_duplicates()

products["number"] = products["SKU_ID"].str.replace("SKU_", "").astype(int)

products = products.sort_values("number")

products = products.drop("number", axis=1)

products = products.reset_index(drop=True)

products.head(10)

   SKU_ID
0   SKU_1
1   SKU_2
2   SKU_3
3   SKU_4
4   SKU_5
5   SKU_6
6   SKU_7
7   SKU_8
8   SKU_9
9  SKU_10

In [32]:
product_catalog = {
    "Electronics": {
        "brands": [
            "Samsung", "Sony", "Dell", "HP",
            "Lenovo", "Asus", "LG", "Logitech"
        ],
        "products": [
            "Laptop", "Monitor", "Keyboard",
            "Mouse", "Tablet", "Headphones",
            "Speaker", "Webcam", "Router", "SSD"
        ]
    },

    "Home & Kitchen": {
        "brands": [
            "Prestige", "Philips", "Bajaj",
            "Havells", "Pigeon", "Butterfly"
        ],
        "products": [
            "Mixer", "Microwave", "Air Fryer",
            "Rice Cooker", "Electric Kettle",
            "Toaster", "Juicer", "Blender",
            "Vacuum Cleaner", "Coffee Maker"
        ]
    },

    "Furniture": {
        "brands": [
            "Godrej", "IKEA", "Nilkamal",
            "Durian", "Urban Ladder"
        ],
        "products": [
            "Office Chair", "Study Table",
            "Bookshelf", "Wardrobe", "Dining Table",
            "TV Unit", "Sofa", "Bed", "Cabinet"
        ]
    },

    "Fashion": {
        "brands": [
            "Nike", "Adidas", "Puma",
            "Levis", "H&M", "Zara"
        ],
        "products": [
            "T-Shirt", "Jeans", "Jacket",
            "Shirt", "Dress", "Hoodie",
            "Shorts", "Cap", "Belt"
        ]
    },

    "Footwear": {
        "brands": [
            "Nike", "Adidas", "Puma",
            "Skechers", "Bata", "Woodland"
        ],
        "products": [
            "Running Shoes", "Sneakers",
            "Boots", "Sandals", "Slippers",
            "Formal Shoes", "Sports Shoes",
            "Loafers"
        ]
    },

    "Sports & Fitness": {
        "brands": [
            "Nivia", "Yonex", "Cosco",
            "Decathlon", "SG"
        ],
        "products": [
            "Football", "Cricket Bat",
            "Tennis Racket", "Yoga Mat",
            "Dumbbells", "Basketball",
            "Skipping Rope", "Gym Gloves"
        ]
    },

    "Beauty & Personal Care": {
        "brands": [
            "Nivea", "Lakme", "L'Oreal",
            "Dove", "Cetaphil"
        ],
        "products": [
            "Face Wash", "Moisturizer",
            "Lipstick", "Perfume", "Shampoo",
            "Conditioner", "Body Lotion",
            "Face Cream"
        ]
    },

    "Toys": {
        "brands": [
            "Lego", "Hot Wheels",
            "Funskool", "Mattel", "Hasbro"
        ],
        "products": [
            "Building Blocks", "Puzzle",
            "Toy Car", "Action Figure",
            "Doll", "Board Game",
            "Remote Car", "Soft Toy"
        ]
    }
}

In [33]:
categories = list(product_catalog.keys())

product_master = []

for i, sku in enumerate(products["SKU_ID"]):

    category = categories[i % len(categories)]

    brand = product_catalog[category]["brands"][
        i % len(product_catalog[category]["brands"])
    ]

    product = product_catalog[category]["products"][
        i % len(product_catalog[category]["products"])
    ]

    product_master.append([
        sku,
        f"{brand} {product}",
        brand,
        category
    ])

product_master = pd.DataFrame(
    product_master,
    columns=[
        "SKU_ID",
        "Product_Name",
        "Brand",
        "Category"
    ]
)

product_master.head(10)

   SKU_ID          Product_Name     Brand                Category
0   SKU_1        Samsung Laptop   Samsung             Electronics
1   SKU_2     Philips Microwave   Philips          Home & Kitchen
2   SKU_3    Nilkamal Bookshelf  Nilkamal               Furniture
3   SKU_4           Levis Shirt     Levis                 Fashion
4   SKU_5         Bata Slippers      Bata                Footwear
5   SKU_6      Nivia Basketball     Nivia        Sports & Fitness
6   SKU_7     Lakme Body Lotion     Lakme  Beauty & Personal Care
7   SKU_8     Funskool Soft Toy  Funskool                    Toys
8   SKU_9        Samsung Router   Samsung             Electronics
9  SKU_10  Havells Coffee Maker   Havells          Home & Kitchen

In [34]:
duplicates = product_master["Product_Name"].duplicated(keep=False)

product_master.loc[duplicates, "Product_Name"] = (
    product_master.loc[duplicates, "Product_Name"]
    + " "
    + product_master.loc[duplicates, "SKU_ID"]
)

In [35]:
print("Number of rows:", len(product_master))

print(
    "Duplicate SKUs:",
    product_master["SKU_ID"].duplicated().sum()
)

print(
    "Duplicate Product Names:",
    product_master["Product_Name"].duplicated().sum()
)

print(
    "Missing values:",
    product_master.isnull().sum().sum()
)

Number of rows: 50
Duplicate SKUs: 0
Duplicate Product Names: 0
Missing values: 0

In [36]:
print(product_master.shape)
print(product_master.isnull().sum())
print(product_master["SKU_ID"].duplicated().sum())

(50, 4)
SKU_ID          0
Product_Name    0
Brand           0
Category        0
dtype: int64
0

In [37]:
product_master

    SKU_ID              Product_Name         Brand                Category
0    SKU_1      Samsung Laptop SKU_1       Samsung             Electronics
1    SKU_2         Philips Microwave       Philips          Home & Kitchen
2    SKU_3        Nilkamal Bookshelf      Nilkamal               Furniture
3    SKU_4               Levis Shirt         Levis                 Fashion
4    SKU_5       Bata Slippers SKU_5          Bata                Footwear
5    SKU_6    Nivia Basketball SKU_6         Nivia        Sports & Fitness
6    SKU_7   Lakme Body Lotion SKU_7         Lakme  Beauty & Personal Care
7    SKU_8   Funskool Soft Toy SKU_8      Funskool                    Toys
8    SKU_9      Samsung Router SKU_9       Samsung             Electronics
9   SKU_10      Havells Coffee Maker       Havells          Home & Kitchen
10  SKU_11        Godrej Study Table        Godrej               Furniture
11  SKU_12               Zara Jacket          Zara                 Fashion
12  SKU_13      Nike Slippers SKU_13          Nike                Footwear
13  SKU_14      Decathlon Basketball     Decathlon        Sports & Fitness
14  SKU_15      Cetaphil Body Lotion      Cetaphil  Beauty & Personal Care
15  SKU_16             Lego Soft Toy          Lego                    Toys
16  SKU_17           Samsung Speaker       Samsung             Electronics
17  SKU_18         Butterfly Blender     Butterfly          Home & Kitchen
18  SKU_19       Durian Office Chair        Durian               Furniture
19  SKU_20              Adidas Jeans        Adidas                 Fashion
20  SKU_21      Puma Slippers SKU_21          Puma                Footwear
21  SKU_22          Yonex Basketball         Yonex        Sports & Fitness
22  SKU_23       L'Oreal Body Lotion       L'Oreal  Beauty & Personal Care
23  SKU_24           Mattel Soft Toy        Mattel                    Toys
24  SKU_25            Samsung Tablet       Samsung             Electronics
25  SKU_26           Philips Toaster       Philips          Home & Kitchen
26  SKU_27              IKEA Cabinet          IKEA               Furniture
27  SKU_28             Levis T-Shirt         Levis                 Fashion
28  SKU_29      Bata Slippers SKU_29          Bata                Footwear
29  SKU_30             SG Basketball            SG        Sports & Fitness
30  SKU_31         Nivea Body Lotion         Nivea  Beauty & Personal Care
31  SKU_32       Hot Wheels Soft Toy    Hot Wheels                    Toys
32  SKU_33          Samsung Keyboard       Samsung             Electronics
33  SKU_34       Havells Rice Cooker       Havells          Home & Kitchen
34  SKU_35          Urban Ladder Bed  Urban Ladder               Furniture
35  SKU_36                 Zara Belt          Zara                 Fashion
36  SKU_37      Nike Slippers SKU_37          Nike                Footwear
37  SKU_38          Cosco Basketball         Cosco        Sports & Fitness
38  SKU_39          Dove Body Lotion          Dove  Beauty & Personal Care
39  SKU_40           Hasbro Soft Toy        Hasbro                    Toys
40  SKU_41     Samsung Laptop SKU_41       Samsung             Electronics
41  SKU_42       Butterfly Microwave     Butterfly          Home & Kitchen
42  SKU_43             Nilkamal Sofa      Nilkamal               Furniture
43  SKU_44                Adidas Cap        Adidas                 Fashion
44  SKU_45      Puma Slippers SKU_45          Puma                Footwear
45  SKU_46   Nivia Basketball SKU_46         Nivia        Sports & Fitness
46  SKU_47  Lakme Body Lotion SKU_47         Lakme  Beauty & Personal Care
47  SKU_48  Funskool Soft Toy SKU_48      Funskool                    Toys
48  SKU_49     Samsung Router SKU_49       Samsung             Electronics
49  SKU_50      Philips Coffee Maker       Philips          Home & Kitchen

In [38]:
product_master.to_csv(
    "../content/product_master.csv",
    index=False
)

print("product_master.csv created successfully!")

product_master.csv created successfully!

In [39]:
df_product_master=pd.read_csv("/content/product_master.csv")
print(f"Rows & Columns : {df_product_master.shape}")
print(df_product_master.head())

Rows & Columns : (50, 4)
  SKU_ID          Product_Name     Brand        Category
0  SKU_1  Samsung Laptop SKU_1   Samsung     Electronics
1  SKU_2     Philips Microwave   Philips  Home & Kitchen
2  SKU_3    Nilkamal Bookshelf  Nilkamal       Furniture
3  SKU_4           Levis Shirt     Levis         Fashion
4  SKU_5   Bata Slippers SKU_5      Bata        Footwear

## Conclusion drawn after running data enrichment on our Original dataset

In [ ]:
# Since we got :
# WH_1 → 4 regions
# WH_2 → 4 regions
# WH_3 → 4 regions
# WH_4 → 4 regions
# WH_5 → 4 regions

# Warehouse_ID → Region
# is NOT a valid functional dependency.

# Therefore, we cannot create:

# Warehouses
# '-----------'
# Warehouse_ID
# Region

# and assume one region per warehouse.

# This tells us something interesting about the dataset: Region behaves like a transaction-level attribute rather than a fixed warehouse attribute.

In [ ]:
# Since we got :
# SUP_1     12
# SUP_2     11
# SUP_3     12
# ...
# SUP_8     13

# So a supplier has multiple lead times.

# Therefore:

# Supplier_ID → Supplier_Lead_Time_Days
# is also NOT valid.

# We shouldn't create a Suppliers table with a single lead time per supplier.

In [ ]:
# Every SKU has:
# 5 different Unit_Cost values

# Therefore:

# SKU_ID → Unit_Cost

# is invalid.

In [ ]:
# Same situation:

# SKU_ID → Unit_Price

# is invalid.

In [ ]:
# Again:

# SKU_ID → Reorder_Point

# is invalid.

In [ ]:
# We found out :
# sku_warehouse_reorder.max()
#         ↓
#         1

# So:

# SKU_ID + Warehouse_ID
#               ↓
#        Reorder_Point

# is a valid dependency based on the current test.

# Therfore: the reorder point belongs to an inventory-level relationship rather than the product master.

In [ ]:
# Stockout_Flag = 0 for all 91,250 records.

# Therefore we should not use stockout rate as a project KPI.

# We'll instead use things like:

# Inventory < Reorder Point

# for inventory-risk analysis.

## For promotion analysis

Difference:

≈ 27.73% higher average units sold during promotion records.

[ Average units sold was 27.7% higher during promotion periods. ]